GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/notes/someInvalidId

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "Ensure that everything still works",
    "important": true
}